# Generated by Django 6.0.4 on 2026-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews_count', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=100, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('all_photos', models.JSONField(blank=True, default=list)),
                ('all_product_details', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
